package com.msg.utils;

public class SystemMessage {

    public class Submit {

        public static final String
            AID_COULD_NOT_BE_NULL = "{Submit.AID_COULD_NOT_BE_NULL}",
            CHANNELID_COULD_NOT_BE_NULL = "{Submit.CHANNELID_COULD_NOT_BE_NULL}",
            DATE_FORMAT_ERROR = "{Submit.DATE_FORMAT_ERROR}",
            EMAIL_COMPOSE_ERROR = "{Submit.EMAIL_COMPOSE_ERROR}",
            EMAIL_COULD_NOT_BE_EMPTY = "{Submit.EMAIL_COULD_NOT_BE_EMPTY}",
            EMAIL_LENGTH_ERROR = "{Submit.EMAIL_LENGTH_ERROR}",
            INDATE_ERROR = "{Submit.INDATE_ERROR}",
            MESSAGE_CONTENT_COULD_NOT_BE_EMPTY = "{Submit.MESSAGE_CONTENT_COULD_NOT_BE_EMPTY}",
            MESSAGE_TITLE_COULD_NOT_BE_EMPTY = "{Submit.MESSAGE_TITLE_COULD_NOT_BE_EMPTY}",
            PASSWORD_COULD_NOT_BE_EMPTY = "{Submit.PASSWORD_COULD_NOT_BE_EMPTY}",
            PHONE_NUMBER_COMPOSE_ERROR = "{Submit.PHONE_NUMBER_COMPOSE_ERROR}",
            PHONE_NUMBER_COULD_NOT_BE_EMPTY = "{Submit.PHONE_NUMBER_COULD_NOT_BE_EMPTY}",
            PHONE_NUMBER_LENGTH_ERROR = "{Submit.PHONE_NUMBER_LENGTH_ERROR}",
            SUBMIT_CONTENT_TOO_BIG = "{Submit.SUBMIT_CONTENT_TOO_BIG}",
            USERID_COULD_NOT_BE_NULL = "{Submit.USERID_COULD_NOT_BE_NULL}",
            USERNAME_COULD_NOT_BE_EMPTY = "{Submit.USERNAME_COULD_NOT_BE_EMPTY}";
    }
    public class Hint {

        public static final String
            BAIDU_PUSH_ERROR = "{Hint.BAIDU_PUSH_ERROR}",
            CFG_UPDATE_SUCCESSFUL = "{Hint.CFG_UPDATE_SUCCESSFUL}",
            ID_HAS_NOT_EXIST = "{Hint.ID_HAS_NOT_EXIST}",
            LOGIN_SUCCESSFUL = "{Hint.LOGIN_SUCCESSFUL}",
            MESSAGE_HAS_SEND = "{Hint.MESSAGE_HAS_SEND}",
            NOT_SUPPORT_CHANNEL = "{Hint.NOT_SUPPORT_CHANNEL}",
            PASSWORD_DO_NOT_MATCH = "{Hint.PASSWORD_DO_NOT_MATCH}",
            PRIVATE_MESSAGE_HAVE_TO_SET_SENDER = "{Hint.PRIVATE_MESSAGE_HAVE_TO_SET_SENDER}",
            UNEXPECTED_EXCEPTION = "{Hint.UNEXPECTED_EXCEPTION}",
            USERNAME_HAS_EXIST = "{Hint.USERNAME_HAS_EXIST}",
            USERNAME_HAS_NOT_EXIST = "{Hint.USERNAME_HAS_NOT_EXIST}",
            USER_HAS_BEEN_NOT_LOGIN = "{Hint.USER_HAS_BEEN_NOT_LOGIN}";
    }
}