package com.msg.utils;

public class SystemMessage {

    public class Hint {

        public static final String
            AID_COULD_NOT_BE_NULL = "{Hint.AID_COULD_NOT_BE_NULL}",
            BAIDU_PUSH_ERROR = "{Hint.BAIDU_PUSH_ERROR}",
            CFG_UPDATE_SUCCESSFUL = "{Hint.CFG_UPDATE_SUCCESSFUL}",
            CHANNELID_COULD_NOT_BE_NULL = "{Hint.CHANNELID_COULD_NOT_BE_NULL}",
            DATE_FORMAT_ERROR = "{Hint.DATE_FORMAT_ERROR}",
            EMAIL_COMPOSE_ERROR = "{Hint.EMAIL_COMPOSE_ERROR}",
            EMAIL_COULD_NOT_BE_EMPTY = "{Hint.EMAIL_COULD_NOT_BE_EMPTY}",
            EMAIL_LENGTH_ERROR = "{Hint.EMAIL_LENGTH_ERROR}",
            ID_HAS_NOT_EXIST = "{Hint.ID_HAS_NOT_EXIST}",
            INDATE_ERROR = "{Hint.INDATE_ERROR}",
            LOGIN_SUCCESSFUL = "{Hint.LOGIN_SUCCESSFUL}",
            MESSAGE_CONTENT_COULD_NOT_BE_EMPTY = "{Hint.MESSAGE_CONTENT_COULD_NOT_BE_EMPTY}",
            MESSAGE_HAS_BEEN_DELETED = "{Hint.MESSAGE_HAS_BEEN_DELETED}",
            MESSAGE_HAS_BEEN_UPDATED = "{Hint.MESSAGE_HAS_BEEN_UPDATED}",
            MESSAGE_HAS_NOT_EXIST = "{Hint.MESSAGE_HAS_NOT_EXIST}",
            MESSAGE_HAS_SEND = "{Hint.MESSAGE_HAS_SEND}",
            MESSAGE_TITLE_COULD_NOT_BE_EMPTY = "{Hint.MESSAGE_TITLE_COULD_NOT_BE_EMPTY}",
            MSGID_COULD_NOT_BE_NULL = "{Hint.MSGID_COULD_NOT_BE_NULL}",
            NOT_SUPPORT_CHANNEL = "{Hint.NOT_SUPPORT_CHANNEL}",
            PASSWORD_COULD_NOT_BE_EMPTY = "{Hint.PASSWORD_COULD_NOT_BE_EMPTY}",
            PASSWORD_DO_NOT_MATCH = "{Hint.PASSWORD_DO_NOT_MATCH}",
            PHONE_NUMBER_COMPOSE_ERROR = "{Hint.PHONE_NUMBER_COMPOSE_ERROR}",
            PHONE_NUMBER_COULD_NOT_BE_EMPTY = "{Hint.PHONE_NUMBER_COULD_NOT_BE_EMPTY}",
            PHONE_NUMBER_LENGTH_ERROR = "{Hint.PHONE_NUMBER_LENGTH_ERROR}",
            PRIVATE_MESSAGE_HAVE_TO_SET_SENDER = "{Hint.PRIVATE_MESSAGE_HAVE_TO_SET_SENDER}",
            RECID_COULD_NOT_BE_NULL = "{Hint.RECID_COULD_NOT_BE_NULL}",
            SENDERNAME_COULD_NOT_BE_NULL = "{Hint.SENDERNAME_COULD_NOT_BE_NULL}",
            SENDID_COULD_NOT_BE_NULL = "{Hint.SENDID_COULD_NOT_BE_NULL}",
            SEND_CHANNEL_COULD_NOT_BE_NULL = "{Hint.SEND_CHANNEL_COULD_NOT_BE_NULL}",
            SUBMIT_CONTENT_TOO_BIG = "{Hint.SUBMIT_CONTENT_TOO_BIG}",
            UNEXPECTED_EXCEPTION = "{Hint.UNEXPECTED_EXCEPTION}",
            USERID_COULD_NOT_BE_NULL = "{Hint.USERID_COULD_NOT_BE_NULL}",
            USERNAME_COULD_NOT_BE_EMPTY = "{Hint.USERNAME_COULD_NOT_BE_EMPTY}",
            USERNAME_HAS_EXIST = "{Hint.USERNAME_HAS_EXIST}",
            USERNAME_HAS_NOT_EXIST = "{Hint.USERNAME_HAS_NOT_EXIST}",
            USER_HAS_BEEN_NOT_LOGIN = "{Hint.USER_HAS_BEEN_NOT_LOGIN}";
    }
}