package com.msg.utils;

public class SystemMessage {

    public class Submit {

        public static final String
            AUTHENTICATION_CODE_COULD_NOT_BE_EMPTY = "{Submit.AUTHENTICATION_CODE_COULD_NOT_BE_EMPTY}",
            AUTHENTICATION_WAY_NOT_SUPPORT = "{Submit.AUTHENTICATION_WAY_NOT_SUPPORT}",
            EMAIL_COMPOSE_ERROR = "{Submit.EMAIL_COMPOSE_ERROR}",
            EMAIL_COULD_NOT_BE_EMPTY = "{Submit.EMAIL_COULD_NOT_BE_EMPTY}",
            EMAIL_LENGTH_ERROR = "{Submit.EMAIL_LENGTH_ERROR}",
            INVITATION_CODE_COULD_NOT_BE_EMPTY = "{Submit.INVITATION_CODE_COULD_NOT_BE_EMPTY}",
            INVITE_CODE_ANSWER_COULD_NOT_BE_EMPTY = "{Submit.INVITE_CODE_ANSWER_COULD_NOT_BE_EMPTY}",
            INVITE_CODE_QUESTION_COULD_NOT_BE_EMPTY = "{Submit.INVITE_CODE_QUESTION_COULD_NOT_BE_EMPTY}",
            KAMPONG_INTRODUCTION_COULD_NOT_BE_EMPTY = "{Submit.KAMPONG_INTRODUCTION_COULD_NOT_BE_EMPTY}",
            KAMPONG_NAME_COULD_NOT_BE_EMPTY = "{Submit.KAMPONG_NAME_COULD_NOT_BE_EMPTY}",
            KAMPONG_TOTEM_COULD_NOT_BE_NULL = "{Submit.KAMPONG_TOTEM_COULD_NOT_BE_NULL}",
            NEW_PASSWORD_COULD_NOT_BE_EMPTY = "{Submit.NEW_PASSWORD_COULD_NOT_BE_EMPTY}",
            NEW_PASSWORD_LENGTH_ERROR = "{Submit.NEW_PASSWORD_LENGTH_ERROR}",
            OLD_PASSWORD_COULD_NOT_BE_EMPTY = "{Submit.OLD_PASSWORD_COULD_NOT_BE_EMPTY}",
            PASSWORD_COULD_NOT_BE_EMPTY = "{Submit.PASSWORD_COULD_NOT_BE_EMPTY}",
            PASSWORD_LENGTH_ERROR = "{Submit.PASSWORD_LENGTH_ERROR}",
            PHONE_NUMBER_COMPOSE_ERROR = "{Submit.PHONE_NUMBER_COMPOSE_ERROR}",
            PHONE_NUMBER_COULD_NOT_BE_EMPTY = "{Submit.PHONE_NUMBER_COULD_NOT_BE_EMPTY}",
            PHONE_NUMBER_LENGTH_ERROR = "{Submit.PHONE_NUMBER_LENGTH_ERROR}",
            PORTRAIT_IMAGE_SIZE_IS_TOO_BIG = "{Submit.PORTRAIT_IMAGE_SIZE_IS_TOO_BIG}",
            QQ_COMPOSE_ERROR = "{Submit.QQ_COMPOSE_ERROR}",
            QQ_COULD_NOT_BE_EMPTY = "{Submit.QQ_COULD_NOT_BE_EMPTY}",
            QQ_LENGTH_ERROR = "{Submit.QQ_LENGTH_ERROR}",
            REALNAME_COMPOSE_ERROR = "{Submit.REALNAME_COMPOSE_ERROR}",
            REALNAME_COULD_NOT_BE_EMPTY = "{Submit.REALNAME_COULD_NOT_BE_EMPTY}",
            REALNAME_LENGTH_ERROR = "{Submit.REALNAME_LENGTH_ERROR}",
            SUBMIT_CONTENT_TOO_BIG = "{Submit.SUBMIT_CONTENT_TOO_BIG}",
            UPLOAD_FILE_COULD_NOT_BE_EMPTY = "{Submit.UPLOAD_FILE_COULD_NOT_BE_EMPTY}",
            USERNAME_COMPOSE_ERROR = "{Submit.USERNAME_COMPOSE_ERROR}",
            USERNAME_COULD_NOT_BE_EMPTY = "{Submit.USERNAME_COULD_NOT_BE_EMPTY}",
            USERNAME_LENGTH_ERROR = "{Submit.USERNAME_LENGTH_ERROR}";
}
    public class Hint {

        public static final String
            FILE_DATA_COULD_NOT_BE_NULL = "{Hint.FILE_DATA_COULD_NOT_BE_NULL}",
            FILE_SAVE_ERROR = "{Hint.FILE_SAVE_ERROR}",
            FILE_TYPE_COULD_NOT_BE_SAVE = "{Hint.FILE_TYPE_COULD_NOT_BE_SAVE}",
            ID_HAS_NOT_EXIST = "{Hint.ID_HAS_NOT_EXIST}",
            INVITATION_CODE_ANSWER_ERROR = "{Hint.INVITATION_CODE_ANSWER_ERROR}",
            INVITATION_CODE_CREATE_SUCCESS = "{Hint.INVITATION_CODE_CREATE_SUCCESS}",
            INVITATION_CODE_NEED_VALIDATE = "{Hint.INVITATION_CODE_NEED_VALIDATE}",
            INVITATION_CODE_NOT_EXIST = "{Hint.INVITATION_CODE_NOT_EXIST}",
            INVITATION_CODE_USERMOUNT_RUN_OUT = "{Hint.INVITATION_CODE_USERMOUNT_RUN_OUT}",
            KAMPONG_CREATE_SUCCESS = "{Hint.KAMPONG_CREATE_SUCCESS}",
            KAMPONG_UPDATE_SUCCESS = "{Hint.KAMPONG_UPDATE_SUCCESS}",
            LOGOUT_SUCCESSFUL = "{Hint.LOGOUT_SUCCESSFUL}",
            MISS_COMPULSORY_FIELDS = "{Hint.MISS_COMPULSORY_FIELDS}",
            NO_CORRESPOND_PERMISSION = "{Hint.NO_CORRESPOND_PERMISSION}",
            OLD_PASSWORD_NOT_MATCH = "{Hint.OLD_PASSWORD_NOT_MATCH}",
            OPERATION_SUCCESS = "{Hint.OPERATION_SUCCESS}",
            PASSWORD_DO_NOT_MATCH = "{Hint.PASSWORD_DO_NOT_MATCH}",
            PASSWORD_HAS_BEEN_UPDATED = "{Hint.PASSWORD_HAS_BEEN_UPDATED}",
            PORTRAIT_HAS_BEEN_UPDATED = "{Hint.PORTRAIT_HAS_BEEN_UPDATED}",
            PORTRAIT_IMAGE_TYPE_NOT_ALLOWED_UPLOAD = "{Hint.PORTRAIT_IMAGE_TYPE_NOT_ALLOWED_UPLOAD}",
            REAL_VERIFY_CODE_ERROR_OR_EXPIREIN = "{Hint.REAL_VERIFY_CODE_ERROR_OR_EXPIREIN}",
            REAL_VERIFY_CODE_HAS_BEEN_SENDED = "{Hint.REAL_VERIFY_CODE_HAS_BEEN_SENDED}",
            REAL_VERIFY_CODE_HAS_BEEN_SENDED_PLEASE_WAIT = "{Hint.REAL_VERIFY_CODE_HAS_BEEN_SENDED_PLEASE_WAIT}",
            REAL_VERIFY_SUCCESS = "{Hint.REAL_VERIFY_SUCCESS}",
            REGISTER_SUCCESS = "{Hint.REGISTER_SUCCESS}",
            ROLE_NOT_EXIST = "{Hint.ROLE_NOT_EXIST}",
            UNEXPECTED_EXCEPTION = "{Hint.UNEXPECTED_EXCEPTION}",
            USERAPPLY_HAS_SUBMITED_PLEASE_WAIT = "{Hint.USERAPPLY_HAS_SUBMITED_PLEASE_WAIT}",
            USERNAME_HAS_EXIST = "{Hint.USERNAME_HAS_EXIST}",
            USERNAME_HAS_NOT_EXIST = "{Hint.USERNAME_HAS_NOT_EXIST}",
            USERNAME_HAS_REPETITION = "{Hint.USERNAME_HAS_REPETITION}",
            USER_BASE_INFO_HAS_BEEN_UPDATED = "{Hint.USER_BASE_INFO_HAS_BEEN_UPDATED}",
            USER_CONTACT_INFO_HAS_BEEN_UPDATED = "{Hint.USER_CONTACT_INFO_HAS_BEEN_UPDATED}",
            USER_HAS_BEEN_LOCKED = "{Hint.USER_HAS_BEEN_LOCKED}",
            USER_HAS_BEEN_LOGIN = "{Hint.USER_HAS_BEEN_LOGIN}",
            USER_HAS_BEEN_NOT_LOGIN = "{Hint.USER_HAS_BEEN_NOT_LOGIN}",
            USER_INFO_NOT_COMPLETION = "{Hint.USER_INFO_NOT_COMPLETION}",
            USER_LOCATION_INFO_HAS_BEEN_UPDATED = "{Hint.USER_LOCATION_INFO_HAS_BEEN_UPDATED}";
}
    public class Templet {

        public static final String
            REAL_VERIFY_CODE_EMAIL_NOTIFY_CONTENT = "{Templet.REAL_VERIFY_CODE_EMAIL_NOTIFY_CONTENT}",
            REAL_VERIFY_CODE_EMAIL_NOTIFY_SUBJECT = "{Templet.REAL_VERIFY_CODE_EMAIL_NOTIFY_SUBJECT}",
            REAL_VERIFY_CODE_PHONE_NOTIFY_CONTENT = "{Templet.REAL_VERIFY_CODE_PHONE_NOTIFY_CONTENT}",
            REAL_VERIFY_CODE_PHONE_NOTIFY_SUBJECT = "{Templet.REAL_VERIFY_CODE_PHONE_NOTIFY_SUBJECT}";
}
}